---
- hosts: all
  become: yes
 
  tasks:

  - name: resolve
    shell: echo "nameserver 10.0.80.12" > /etc/origin/node/resolv.conf

  - name: status
    shell: cat /etc/origin/node/resolv.conf
    register: output

  - debug: var=output.stdout_lines
